### ISSUE TITLE
AutoFishing v1.16 is not working in 1.21.10 - Requesting  an update please.

### ISSUE THREAD

**Issue by JCorpse2025** [WMGameLive/AutoFishing#12]
AutoFishing v1.16 is not working in 1.21.10 - Requesting  an update please.

18.10 10:24:46 [Server] WARN [AutoFishing] Task #20491 for AutoFishing v1.16 generated an exception
18.10 10:24:46 [Server] INFO java.lang.NoSuchMethodError: 'net.minecraft.server.level.ServerLevel net.minecraft.server.level.ServerPlayer.y()'
18.10 10:24:46 [Server] INFO at AutoFishing-1.16.jar/wm.vdr.autofishing.Listeners.doRightClick(Listeners.java:57) ~[AutoFishing-1.16.jar:?]
18.10 10:24:46 [Server] INFO at AutoFishing-1.16.jar/wm.vdr.autofishing.Listeners.lambda$onFishing$0(Listeners.java:38) ~[AutoFishing-1.16.jar:?]
18.10 10:24:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1749) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1623) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickServer(DedicatedServer.java:430) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1343) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:383) ~[paper-1.21.10.jar:1.21.10-81-7845cba]
18.10 10:24:46 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by WMGameLive** [comment]
Done.
